name: input_box_with_suggestion
description: A new Flutter project.
version: 0.0.2
homepage: https://github.com/satyambarsainya/input_box_with_suggestion

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.objectx.technologies.input_box_with_suggestion
        pluginClass: InputBoxWithSuggestionPlugin
      ios:
        pluginClass: InputBoxWithSuggestionPlugin
      windows:
        pluginClass: InputBoxWithSuggestionPlugin
